POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvbWlra28iLCJpZCI6IjVmOTU1YTVlNDc2ZTM3NDc5NDEzZDEyMCIsImlhdCI6MTYwMzYyMzU1MH0.pD4oJMqMDvkLu3W64Q1SUOLOAeQHl29p4xAfrFM7RrI

{
     "title": "testi",
    "author": "author",
    "url": "serwerwerwer",
    "likes": 2,
}